// WIRING DETAILS
// RIGHT WHEEL: PIN 10
// LEFT WHEEL: PIN 1
// IPC1: 								RIGHT WHEEL=POSITIVE
// ICP2(DAISY CHAINED):  LEFT WHEEL=NEGATIVE
// CLAW MOTOR: MOTOR PIN 2
// BUTTON1: DIGITAL 1
// BUTTON2: DIGITAL 2
#ifndef HEADER_ROBOT
#define HEADER_ROBOT

#define CLAW_TIME 200
#define CLAW_SPEED 30

#define FORWARD_TIME 2000
#define BACKWARD_TIME 2000

#define FASTSPEED 90
#define MEDIUMSPEED 40
#define SLOWSPEED 20
#define MOTOR_SPEED_OFFSET 7 // THE RIGHT WHEEL MOVES FASTER. SLOW IT DOWN

// STATE MACHINE STATES
typedef enum T_state
{
  STATE_IDLE = 0,
  STATE_OPENING,
  STATE_CLOSING,
  STATE_FORWARD,
  STATE_BACKWARD,
} T_state;
// DATA PASSED TO AND ALTERED IN EACH STATE
typedef struct {
	int button1_pushed;
	int button2_pushed;
} RobotControl;

#endif
