// WIRING DETAILS
// RIGHT WHEEL: PIN 10
// LEFT WHEEL: PIN 1
// IPC1: 								RIGHT WHEEL=POSITIVE
// ICP2(DAISY CHAINED):  LEFT WHEEL=NEGATIVE
// CLAW MOTOR: MOTOR PIN 2
// BUTTON1: DIGITAL 1
// BUTTON2: DIGITAL 2
#ifndef HEADER_ROBOT
#define HEADER_ROBOT

// STATE MACHINE STATES
typedef enum T_state
{
  STATE_IDLE = 0,
  STATE_OPENING,
  STATE_CLOSING,
} T_state;
// DATA PASSED TO AND ALTERED IN EACH STATE
typedef struct {
	int button1_pushed;
	int button2_pushed;
} RobotControl;

#endif
