// WIRING DETAILS
// RIGHT WHEEL: PIN 10
// LEFT WHEEL: PIN 1
// IPC1: 								RIGHT WHEEL=POSITIVE
// ICP2(DAISY CHAINED):  LEFT WHEEL=NEGATIVE
// BUTTON1: DIGITAL 1
// BUTTON2: DIGITAL 2
#ifndef HEADER_ROBOT
#define HEADER_ROBOT

// CONSTANTS
#define FASTSPEED 90
#define MEDIUMSPEED 20
#define SLOWSPEED 15
#define MOTOR_SPEED_OFFSET 5 // THE RIGHT WHEEL MOVES FASTER. SLOW IT DOWN
// AMOUNT OF ENCODER TICKS ROBOT NEEDS TO DO FOR MOVING/TURNING STATES:
#define ONEMETRE 2000
#define NINETYDEG 550
// STATE MACHINE STATES
typedef enum T_state
{
  STATE_IDLE = 0,
  STATE_TURNING,
  STATE_MOVING
} T_state;
// DATA PASSED TO AND ALTERED IN EACH STATE
typedef struct {
	int button1_pushed;
	int button2_pushed;
} RobotControl;

#endif
