// WIRING DETAILS
// RIGHT WHEEL: PIN 10
// LEFT WHEEL: PIN 1
// IPC1: 								RIGHT WHEEL=POSITIVE
// ICP2(DAISY CHAINED):  LEFT WHEEL=NEGATIVE
// CLAW MOTOR: MOTOR PIN 2
// BUTTON1: DIGITAL 1
// BUTTON2: DIGITAL 2
#ifndef HEADER_ROBOT
#define HEADER_ROBOT

#define CLAW_TIME 200 // opening and closing
#define CLAW_SPEED 30

#define FORWARD_TIME 2000
#define BACKWARD_TIME 2000
#define TURNAWAY_TIME 3200
#define BACKAWAY_TIME 972

#define NINETYDEG_ISH 972

#define FASTSPEED 90
#define MEDIUMSPEED 40
#define SLOWSPEED 20
// THE RIGHT WHEEL MOVES FASTER. SLOW IT DOWN
#define MOTOR_SPEED_OFFSET 7 
// STATE MACHINE T_states
typedef enum T_state
{
  STATE_IDLE = 0,
  STATE_TOGGLECLAW,
  STATE_OPENING,
  STATE_FORWARD,
  STATE_BACKWARD,
  STATE_TURNAWAY,
  STATE_BACKAWAY,
} T_state;
// DATA PASSED TO AND ALTERED IN EACH STATE
typedef struct {
	bool button1_pushed;
	bool button2_pushed;
	bool toggle_flag;
} RobotControl;
#endif
