#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    IRSensor,       sensorReflection)
#pragma config(Sensor, dgtl1,  Button1,        sensorTouch)
#pragma config(Sensor, dgtl2,  Button2,        sensorTouch)
#pragma config(Sensor, dgtl3,  LimitLeft,      sensorTouch)
#pragma config(Sensor, dgtl4,  LimitRight,     sensorTouch)
#pragma config(Sensor, dgtl8,  Sonar,          sensorSONAR_cm)
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port1,           MLeft,         tmotorVex393_HBridge, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port2,           MClaw,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          MRight,        tmotorVex393_HBridge, openLoop, encoderPort, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

// WIRING DETAILS
// IR SENSOR: ANALOG PIN 1
// RIGHT WHEEL: PIN 10
// LEFT WHEEL: PIN 1
// IPC1: 								RIGHT WHEEL=POSITIVE
// ICP2(DAISY CHAINED):  LEFT WHEEL=NEGATIVE
// CLAW MOTOR: MOTOR PIN 2
// BUTTON1: DIGITAL 1
// BUTTON2: DIGITAL 2
// SONAR: DIGITAL 8 and 9
// Limit Left and Limit Right: 3 and 4
#include "Devices.c"
#include "RobotStates.c"
// PROGRAM STARTS HERE

void driveStraightDistance(int tenthsOfIn, int masterPower)
{

  resetBothEncoders();
  int tickGoal = (42 * tenthsOfIn) / 10;

  //This will count up the total encoder ticks despite the fact that the encoders are constantly reset.
  int totalTicks = 0;

  //Initialise slavePower as masterPower - 5 so we don't get huge error for the first few iterations. The
  //-5 value is based off a rough guess of how much the motors are different, which prevents the robot from
  //veering off course at the start of the function.
  int slavePower = masterPower - 5;

  int error = 0;

  int kp = 5;

  resetBothEncoders();
//  SensorValue[leftEncoder] = 0;
//  SensorValue[rightEncoder] = 0;

  //Monitor 'totalTicks', instead of the values of the encoders which are constantly reset.
  while(abs(totalTicks) < tickGoal)
  {
    //Proportional algorithm to keep the robot going straight.
    motor[MLeft] = masterPower;
    motor[MRight] = slavePower;

//    error = -getMotorEncoder(MLeft) - getMotorEncoder(MRight);

//    slavePower += error / kp;

  resetBothEncoders();
//    SensorValue[leftEncoder] = 0;
//    SensorValue[rightEncoder] = 0;

    wait1Msec(100);

    //Add this iteration's encoder values to totalTicks.
    totalTicks+= abs(getMotorEncoder(MLeft));
  }
  resetBothEncoders();

 // motor[leftServo] = 0; // Stop the loop once the encoders have counted up the correct number of encoder ticks.
 // motor[rightServo] = 0;
}


task main()
{
	driveStraightDistance(500, 40);

  // ROBOT BEGINS IN IDLE STATE
  T_state state;
  state  = STATE_IDLE;
  // ROBOT BEGINS WITH THESE DATA FIELDS SET
  RobotControl control;
   while (true)
  {
    switch(state) // STATE MACHINE
    {
      case STATE_IDLE:
      	state = ProcStateIdle(control);
      break;
      case STATE_WALK:
      	state = ProcStateWalk(control);
      break;
      case STATE_BACKAWAY:
      	state = ProcStateBackaway(control);
      break;
      default: // We should never be in this state.
    }
  }
}
