#ifndef ROBOT_STATE_H
#define ROBOT_STATE_H

// THE ROBOTS BEHAVIOR IS BASED UPON STATE TRANSITIONS OF TYPE ROBOT_STATE
typedef enum Robot_state_tag
{
  STATE_IDLE = 0,   // PRESSING THE RBUTTON OPENS AND CLOSES THE CLAW HATCH
                    // PRESSING THE LBUTTON SEARCHES, FINDS AND ATTACHES THE CABLE
  STATE_CLAWTOGGLE,  // FOR PLACING THE CABLE (MAGNET APPROACH)
  STATE_SEARCH,     // STAY IN THIS STATE UNTIL YOU HAVE PERFECTLY ALIGNED TO THE CENTER OF THE BEACON
  STATE_ADVANCE,    // WALK FORWARD A LITTLE BIT THEN SEARCH OR APPROACH
  STATE_WALL,       // IF A LIMIT SWITCH IS HIT, BACK UP A BIT AND TURN 90 DEGREES FROM IT
  STATE_APPROACH,   // PERFORMS FOUR ACTIONS IN QUICK SUCCESION TO ATTACH THE CABLE
} Robot_state;

Robot_state robotStateFactory() {
  Robot_state state = STATE_IDLE;
  return state;
}


#endif
