#ifndef ROBOT_STATE_H
#define ROBOT_STATE_H

// THE ROBOTS BEHAVIOR IS BASED UPON STATE TRANSITIONS OF TYPE ROBOT_STATE
typedef enum Robot_state_tag
{
  STATE_IDLE = 0,   // THE FIRST STATE
  STATE_CLAWTOGGLE,  // PRESSING THE RIGHT BUTTON OPENS AND CLOSES THE CLAW
                        // HATCH FOR PLACING THE CABLE (MAGNET APPROACH)
  STATE_SEARCH,     // STAY IN THIS STATE UNTIL YOU HAVE PERFECTLY ALIGNED
                        // TO THE CENTER OF THE BEACON
  STATE_ADVANCE,    // WALK FORWARD A LITTLE BIT
  // TODO: back up if you hit a wall
//  STATE_SWEEP,     // SWEEP UNTIL BEACON IS LOST TO FIND HIGHEST POINT
//  STATE_PINPOINT,     // MOVE TO HIGHEST POINT
//  STATE_WALK,       // WAKING TOWARD THE BEACON STRAIGHTLY UNTIL A TRANSITION OCCURS

  // THE FINAL STEPS FIRE ONE A A TIME TO MAKE CONTACT
  STATE_CLAWOPEN,   // open the claw before attaching
  STATE_APPROACH,
  STATE_CLAWCLOSE,
  STATE_BACKUP,
} Robot_state;

Robot_state robotStateFactory() {
  Robot_state state = STATE_IDLE;
  return state;
}


#endif
